title: 'Niccolò Menegazzo'
default_lang: it
author:
  name: 'Niccolò Menegazzo'
  email: niccolomenegazzoaudio@gmail.com

metadata:
  description: 'Sound Designer · Sound Engineer'

contact:
  email: niccolomenegazzoaudio@gmail.com
  location: Italia
